// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import "time"

const TableNameAccount = "u_account"

// u_account
type Account struct {
	ID       int32     `json:"id" gorm:"column:id"`
	Name     string    `json:"name" gorm:"column:name"`           // 用户姓名-登陆
	Mobile   string    `json:"mobile" gorm:"column:mobile"`       // 手机号码
	Password string    `json:"password" gorm:"column:password"`   // 密码
	Age      int32     `json:"age" gorm:"column:age"`             // 年龄
	Sex      bool      `json:"sex" gorm:"column:sex"`             // 性别
	Type     bool      `json:"type" gorm:"column:type"`           // 账号类型 1:服务账号;2:商家账号;3:会员账号
	Status   bool      `json:"status" gorm:"column:status"`       // 用户状态 1:允许登陆,其他状态后续添加注视
	CreateAt time.Time `json:"create_at" gorm:"column:create_at"` // 创建时间
	UpdateAt time.Time `json:"update_at" gorm:"column:update_at"` // 更新时间
}

// TableName Account's table name
func (*Account) TableName() string {
	return TableNameAccount
}
