server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
  log:
    filePath: /tmp/logs/
    fileName: app.log
    timeLayout: 2006-01-02 15:04:05
data:
  database:
    driver: mysql
    source: db_user:db_pass@tcp(192.168.56.12:3306)/kratos
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
registry:
  nacos:
    address: 127.0.0.1
    port: 8848
    scheme: http
    path: /nacos
    config:
      namespace_id: cf45e213-902a-484f-8f7a-fa61f5c42457
      timeout_ms: 5000
      not_load_cache_at_start: true
      log_dir: /tmp/nacos/log
      cache_dir: /tmp/nacos/log
      rotate_time: 1h
      max_age: 3
      log_level: debug