// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	account2 "github.com/china-xs/kratos-tpl/internal/biz/account"
	"github.com/china-xs/kratos-tpl/internal/conf"
	"github.com/china-xs/kratos-tpl/internal/data"
	"github.com/china-xs/kratos-tpl/internal/data/account"
	"github.com/china-xs/kratos-tpl/internal/data/good"
	"github.com/china-xs/kratos-tpl/internal/server"
	service2 "github.com/china-xs/kratos-tpl/internal/service"
	"github.com/china-xs/kratos-tpl/internal/service/v1/account"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	accountRepo := account.NewAccountRepo(dataData, logger)
	goodRepo := good.NewGoodRepo(dataData, logger)
	logic := account2.NewAccountLogic(logger, accountRepo, goodRepo)
	accountService := service.NewAccountService(logic, logger)
	appService := service2.NewAppService(accountService)
	httpServer := server.NewHTTPServer(confServer, logger, appService)
	grpcServer := server.NewGRPCServer(confServer, logger)
	app := newApp(logger, httpServer, grpcServer)
	return app, func() {
		cleanup()
	}, nil
}
