// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
)

func Use(db *gorm.DB) *Query {
	return &Query{
		db:      db,
		Account: newAccount(db),
	}
}

type Query struct {
	db *gorm.DB

	Account account
}

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		Account: q.Account.clone(db),
	}
}

type queryCtx struct {
	Account accountDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		Account: q.Account.accountDo,
	}
}

func (q *Query) Transaction(fc func(db *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *queryTx {
	return &queryTx{q.clone(q.db.Begin(opts...))}
}

type queryTx struct{ *Query }

func (q *queryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *queryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *queryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *queryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
